version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: product
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/my.cnf
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - my_network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  flask_sync:
    build:
      context: ./flask_sync
      dockerfile: Dockerfile
    container_name: flask-sync-container
    depends_on:
      - mysql
      - elasticsearch
    ports:
      - "5000:5000"
    networks:
      - my_network

volumes:
  mysql_data:
  es_data:

networks:
  my_network:
